### ISSUE TITLE
luatexko breaks Latin font

### ISSUE THREAD

**Issue by s163555** [dohyunkim/luatexko#7]
Hi,
I am using lualatex + luatexko for my thesis as I am required to have some parts in Korean. But primarily the thesis is using Latin characters. For latin characters I am using mlmodern package (from here: https://ctan.org/pkg/mlmodern). Without luatexko I can use mlmodern succesfully. However, when I load luatexko, instead of getting mlmodern font for latin chracters I get the default spindly font, with all typesetting (bold, italics, etc) broken. Is there a way I can use both?

**Comment by dohyunkim** [comment]
As mlmodern package does not seem to support `TU` (unicode) encoding, you need to try a trick. 
Load luatexko package before mlmodern. For instance:
```latex
\documentclass{article}

\usepackage{luatexko}
\setmainhangulfont{Noto Serif CJK KR}[Script=Hangul,Language=Korean,AutoFakeSlant]
\setsanshangulfont{Noto Sans CJK KR}[Script=Hangul,Language=Korean,AutoFakeSlant]

\usepackage[T1]{fontenc}
\usepackage{mlmodern}

\begin{document}

This is a test.
한글 테스트.

\end{document}
```

**Comment by s163555** [comment]
That trick seems to resolve the issue with spindliness. 감사합니다~
